micronaut:
  application:
    name: worker_eventbuilder
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5435/event`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:P@ssw0rd}
    driverClassName: org.postgresql.Driver


jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

rabbitmq:
  uri: amqp://localhost:5672
  username: rabbituser
  password: P@ssw0rd

eventbuilder:
  queue: ${EVENT_QUEUE:eventbuilder.processor.queue}
