micronaut:
  application:
    name: user
  server:
    port: ${API_PORT:8081}
  metrics:
    enabled: false
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/user`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:P@ssw0rd}
    driverClassName: org.postgresql.Driver

consul:
  client:
    registration:
      enabled: true
      check:
        http: true
    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
