micronaut:
  application:
    name: item
  server:
    port : ${API_PORT:8082}
  metrics:
    export:
      prometheus:
        enabled: false
        descriptions: true
        step: PT1M
    enabled: false

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5433/item`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:P@ssw0rd}
    driverClassName: org.postgresql.Driver
consul:
  client:
    registration:
      enabled: true
      check:
        http: true
    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}

tracing:
  zipkin:
    enabled: true
    http:
      url: http://localhost:9411
    sampler:
      probability: 1

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
